#!/bin/bash

PATTERN='^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}\.[0-9]{2}\.[0-9]{2}\.[a-z0-9]+$'

for FILE in "$@"
do
    if echo "$FILE" | egrep -i "$PATTERN" -q ; then
        continue
    fi    
    if [ -d "$FILE" ]; then
        continue
    fi

    EXT=`echo "${FILE##*.}" | tr '[:upper:]' '[:lower:]'`
    DATE=`exiftool -time:CreateDate -d "%Y-%m-%d %H.%M.%S" -s -s -s "$FILE"`
    if [[ "$DATE" ]]; then
        mv -i "$FILE" "$DATE.$EXT"
    fi
done

